import "./globals.css";
import Navbar from "@/components/Navbar";
import ClientProvider from "./ClientProvider";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

export const metadata = {
  title: "ProDex",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" data-theme='light'>
      <body className="bg-base-100">
        <ClientProvider session={session}>
          <Navbar />
          {children}
          <ToastContainer/>
          <Footer/>
        </ClientProvider>
      </body>
    </html>
  );
}
