import "./globals.css";
import Navbar from "@/components/Navbar";
import ClientProvider from "./ClientProvider";

export const metadata = {
  title: "ProDex",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" data-theme='light'>
      <body className="bg-base-100">
        <ClientProvider session={session}>
          <Navbar />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
